### ISSUE TITLE
In fix_leakage_tests branch, not using phase correction makes degraded detection

### ISSUE THREAD

**Issue by robotopia** [CIRA-Pulsars-and-Transients-Group/vcstools#208]
Comparison of a make_beam run using the default behaviour of using antenna 0 as a reference antenna (for dividing the phases of the calibration solution), and turning it off (by choosing reference antenna >127), yields a much degraded (Stokes I) S/N on J0742-2822 (in obs 1165080856), much more than expected.
This issue is part of the broader (ongoing) investigation to verify the polarisation of the beamformer.

**Comment by bwmeyers** [comment]
That branch has now been deleted, so I'm closing this.
