### ISSUE TITLE
Incorrect module import

### ISSUE THREAD

**Issue by bwmeyers** [CIRA-Pulsars-and-Transients-Group/vcstools#226]
`find_pulsar_in_obs.py` imports `pulsar_spectra.catalogues` but the module is called `pulsar_spectra.catalogue` which, of course, raises an error.

**Comment by NickSwainston** [comment]
This is fixed on the devel version, just needs to be merged in

**Comment by bwmeyers** [comment]
I see. Is there a reason it hasn't been merged in yet? I made the fix along with the GitHub actions in #227

**Comment by bwmeyers** [comment]
Never mind, I see these are both changed in the other PR, so I'll link this there, and close my PR.
